package com.example.projectmanagement.utils

const val PROJECT_STATUS_PENDING = "Ongoing"
const val TASK_STATUS_ONGOING = "Assigned"
const val PROJECT_STATUS_COMPLETE= "Completed"
const val TASK_STATUS_CLOSED= "Closed"
const val USER_COLLECTION_REF = "userDetails"
const val USER_ROLE_MANAGER="Manager"
const val USER_ROLE_TEAM_MEMBER="Team Member"
const val INTENT_FROM_PROJECT_LIST="101"
const val INTENT_FROM_TASK_LIST="102"
const val INTENT_FROM_LOGIN="103"
const val INTENT_FROM_PROJECT_DETAILS="104"
const val INTENT_FROM_PRJ_LST_FOR_PRJ="105"
const val INTENT_FROM_READ_PROJECT="107"
const val INETNT_FROM_TEAM_PRJ_LIST= "108"